# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        date

# Setup
title:            moo99
tagline:          'personal log'
description:      're-view life'
url:              http://moo99.github.io/
baseurl:          /

author:
  name:           'Jack Kwon'
  url:            https://twitter.com/kwonhyuckmin

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/moo99
