# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            moo99
tagline:          'personal log'
description:      're-view life'
url:              http://moo99.github.com
baseurl:          /

author:
  name:           'Jack Kwon'
  url:            https://twitter.com/kwonhyuckmin

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
